// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUOwOv2Zcp5Na12r8nDUzl0LzS_5fkid8',
    appId: '1:359599088646:web:7f73699efe3de9a73e8f87',
    messagingSenderId: '359599088646',
    projectId: 'booklyapp-acf0f',
    authDomain: 'booklyapp-acf0f.firebaseapp.com',
    storageBucket: 'booklyapp-acf0f.appspot.com',
    measurementId: 'G-3GQL1TKQBC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASk0jd7s1bxTp1UrOeoLVnRqhwrE-Lbe4',
    appId: '1:359599088646:android:4f99c5c391885e8b3e8f87',
    messagingSenderId: '359599088646',
    projectId: 'booklyapp-acf0f',
    storageBucket: 'booklyapp-acf0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClJEUIKVhMMFIIPKYPECWmYM4GEqOCCjc',
    appId: '1:359599088646:ios:03f8ce3173a05d5a3e8f87',
    messagingSenderId: '359599088646',
    projectId: 'booklyapp-acf0f',
    storageBucket: 'booklyapp-acf0f.appspot.com',
    iosBundleId: 'com.example.booklyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClJEUIKVhMMFIIPKYPECWmYM4GEqOCCjc',
    appId: '1:359599088646:ios:03f8ce3173a05d5a3e8f87',
    messagingSenderId: '359599088646',
    projectId: 'booklyapp-acf0f',
    storageBucket: 'booklyapp-acf0f.appspot.com',
    iosBundleId: 'com.example.booklyapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUOwOv2Zcp5Na12r8nDUzl0LzS_5fkid8',
    appId: '1:359599088646:web:86e1091e5099c9ad3e8f87',
    messagingSenderId: '359599088646',
    projectId: 'booklyapp-acf0f',
    authDomain: 'booklyapp-acf0f.firebaseapp.com',
    storageBucket: 'booklyapp-acf0f.appspot.com',
    measurementId: 'G-MRPP6ZBDBZ',
  );
}
